import About from "@component/components/About";
import Contact from "@component/components/Contact";
import Main from "@component/components/Main";
import Navbar from "@component/components/Navbar";
import Projects from "@component/components/Projects";
import Skills from "@component/components/Skills";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Esther SH Choi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Main />
      <About />
      <Skills />
      <Projects />
      <Contact />
    </>
  );
}
